exports.STATES = [
  { id: 1, name: 'alabama', code: 'AL' },
  { id: 2, name: 'alaska', code: 'AK' },
  { id: 3, name: 'arizona', code: 'AZ' },
  { id: 4, name: 'arkansas', code: 'AR' },
  { id: 5, name: 'california', code: 'CA' },
  { id: 6, name: 'colorado', code: 'CO' },
  { id: 7, name: 'connecticut', code: 'CT' },
  { id: 8, name: 'delaware', code: 'DE' },
  { id: 9, name: 'florida', code: 'FL' },
  { id: 10, name: 'georgia', code: 'GA' },
  { id: 11, name: 'hawaii', code: 'HI' },
  { id: 12, name: 'idaho', code: 'ID' },
  { id: 13, name: 'illinois', code: 'IL' },
  { id: 14, name: 'indiana', code: 'IN' },
  { id: 15, name: 'iowa', code: 'IA' },
  { id: 16, name: 'kansas', code: 'KS' },
  { id: 17, name: 'kentucky', code: 'KY' },
  { id: 18, name: 'louisiana', code: 'LA' },
  { id: 19, name: 'maine', code: 'ME' },
  { id: 20, name: 'maryland', code: 'MD' },
  { id: 21, name: 'massachusetts', code: 'MA' },
  { id: 22, name: 'michigan', code: 'MI' },
  { id: 23, name: 'minnesota', code: 'MN' },
  { id: 24, name: 'mississippi', code: 'MS' },
  { id: 25, name: 'missouri', code: 'MO' },
  { id: 26, name: 'montana', code: 'MT' },
  { id: 27, name: 'nebraska', code: 'NE' },
  { id: 28, name: 'nevada', code: 'NV' },
  { id: 29, name: 'new hampshire', code: 'NH' },
  { id: 30, name: 'new jersey', code: 'NJ' },
  { id: 31, name: 'new mexico', code: 'NM' },
  { id: 32, name: 'new york', code: 'NY' },
  { id: 33, name: 'north carolina', code: 'NC' },
  { id: 34, name: 'north dakota', code: 'ND' },
  { id: 35, name: 'ohio', code: 'OH' },
  { id: 36, name: 'oklahoma', code: 'OK' },
  { id: 37, name: 'oregon', code: 'OR' },
  { id: 38, name: 'pennsylvania', code: 'PA' },
  { id: 39, name: 'rhode island', code: 'RI' },
  { id: 40, name: 'south carolina', code: 'SC' },
  { id: 41, name: 'south dakota', code: 'SD' },
  { id: 42, name: 'tennessee', code: 'TN' },
  { id: 43, name: 'texas', code: 'TX' },
  { id: 44, name: 'utah', code: 'UT' },
  { id: 45, name: 'vermont', code: 'VT' },
  { id: 46, name: 'virginia', code: 'VA' },
  { id: 47, name: 'washington', code: 'WA' },
  { id: 48, name: 'west virginia', code: 'WV' },
  { id: 49, name: 'wisconsin', code: 'WI' },
  { id: 50, name: 'wyoming', code: 'WY' },
];
